[project]
name = "translator-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.40.0",
    "azure-ai-translation-document>=1.1.0",
    "python-docx>=1.1.0",
    "python-dotenv>=1.2.2",
    "requests>=2.31.0",
    "streamlit>=1.55.0",
]
